// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAZWwwzvJEMH4nC1abEAkgSyuly0_jyTk',
    appId: '1:845453395998:web:f4d687b07fee95ddd8c60f',
    messagingSenderId: '845453395998',
    projectId: 'taskwin-ca38c',
    authDomain: 'taskwin-ca38c.firebaseapp.com',
    storageBucket: 'taskwin-ca38c.firebasestorage.app',
    measurementId: 'G-4XBCD38G9N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCpro53_D-NTvNXzY0PhMmA_QLtdXxXEU',
    appId: '1:845453395998:android:edc7b4dcd46272a4d8c60f',
    messagingSenderId: '845453395998',
    projectId: 'taskwin-ca38c',
    storageBucket: 'taskwin-ca38c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGkyFZAx1hDczD3N9UE-bK9bSe_RGiv0A',
    appId: '1:845453395998:ios:f642f29e005b8d0cd8c60f',
    messagingSenderId: '845453395998',
    projectId: 'taskwin-ca38c',
    storageBucket: 'taskwin-ca38c.firebasestorage.app',
    iosBundleId: 'com.example.taskwin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGkyFZAx1hDczD3N9UE-bK9bSe_RGiv0A',
    appId: '1:845453395998:ios:f642f29e005b8d0cd8c60f',
    messagingSenderId: '845453395998',
    projectId: 'taskwin-ca38c',
    storageBucket: 'taskwin-ca38c.firebasestorage.app',
    iosBundleId: 'com.example.taskwin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAZWwwzvJEMH4nC1abEAkgSyuly0_jyTk',
    appId: '1:845453395998:web:20dc61e2aa58036ed8c60f',
    messagingSenderId: '845453395998',
    projectId: 'taskwin-ca38c',
    authDomain: 'taskwin-ca38c.firebaseapp.com',
    storageBucket: 'taskwin-ca38c.firebasestorage.app',
    measurementId: 'G-0SJPY9ZQVD',
  );
}
